# -*- coding: utf-8 -*-
"""Exercicio - Sistemas Lineares 2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1syA1OWj9m4zER34O2YSE-LGFr3Vzsq49

QUESTAO 1
"""

import numpy as np
A = np.array([[2,-1],[4,-2]]) 
B = np.array([5,10])        
Ax= np.array([[5,-1],[10,-2]])  

detA = np.linalg.det(A)
detAx = np.linalg.det(Ax)

if detA !=0:
  S = np.linalg.solve(A,B)
  print(f"Sistema Possivel Determinado  - {S}")
else:
  if detA ==0 and detAx ==0:
    print("Sistema Possivel e Indeterminado")
  else:
    print("Sistema Impossivel")

"""QUESTAO 2"""

A = np.array([[-4,3,1],[1,5,0], [0,-2,6]]) 
B = np.array([1,2,3])        
Ax= np.array([[1,3,1],[2,5, 0], [0, -2, 6]])  

detA = np.linalg.det(A)
detAx = np.linalg.det(Ax)

if detA !=0:
  S = np.linalg.solve(A,B)
  print(f"Sistema Possivel Determinado  - {S}")
else:
  if detA ==0 and detAx ==0:
    print("Sistema Possivel e Indeterminado")
  else:
    print("Sistema Impossivel")

"""QUESTAO 3"""

A = np.array([[1,2,4],[2,-1,2], [3,-3,-1]]) 
B = np.array([5,8,7])        
Ax= np.array([[5,2,4],[8,-1, 2], [7, -3, -1]])  

detA = np.linalg.det(A)
detAx = np.linalg.det(Ax)

if detA !=0:
  S = np.linalg.solve(A,B)
  print(f"Sistema Possivel Determinado  - {S}")
else:
  if detA ==0 and detAx ==0:
    print("Sistema Possivel e Indeterminado")
  else:
    print("Sistema Impossivel")

"""QUESTAO 4"""

A = np.array([[1,2,-1],[2,3,1], [5,3,-2]]) 
B = np.array([8,1,-11])        
Ax= np.array([[8,2,-1],[1,3, 1], [-11, 3, -2]])  

detA = np.linalg.det(A)
detAx = np.linalg.det(Ax)

if detA !=0:
  S = np.linalg.solve(A,B)
  print(f"Sistema Possivel Determinado  - {S}")
else:
  if detA ==0 and detAx ==0:
    print("Sistema Possivel e Indeterminado")
  else:
    print("Sistema Impossivel")

"""QUESTAO 5"""

A = np.array([[0.15, 0.10, 0.06],[1, 1, -1], [1, 1, 1]]) 
B = np.array([20000,0,200000])        
Ax= np.array([[20000,0.10,0.06],[0,1, -1], [200000, 1, 1]])  

detA = np.linalg.det(A)
detAx = np.linalg.det(Ax)

if detA !=0:
  S = np.linalg.solve(A,B)
  print(f"Sistema Possivel Determinado  - {S}")
else:
  if detA ==0 and detAx ==0:
    print("Sistema Possivel e Indeterminado")
  else:
    print("Sistema Impossivel")